#!/usr/bin/env python3
"""Regenerate README illustrations from production QML and a synthetic scene."""
from __future__ import annotations

import argparse
import base64
import hashlib
import json
import math
import os
from pathlib import Path
import shutil
import string
import subprocess
import tempfile
import xml.etree.ElementTree as ET

from PIL import Image

HERE = Path(__file__).resolve().parent
ROOT = HERE.parents[1]
SVG_NS = "http://www.w3.org/2000/svg"
ET.register_namespace("", SVG_NS)


def run(*args, env=None):
    subprocess.run([str(arg) for arg in args], check=True, cwd=ROOT, env=env)


def tray_icon(metadata):
    """Translate the 64-unit steady-state geometry in trayvisual.cpp into vectors.

    The production TrayVisual::build supplies usage, pacing and severity; the
    production QSvgRenderer supplies the same visible logo crop as the app.
    Review this small geometry adapter if trayvisual.cpp's drawing changes.
    """
    tray, colors = metadata["tray"], metadata["colors"]
    parts = [f'<circle cx="32" cy="32" r="26.5" fill="none" '
             f'stroke="{colors["selection"]}" stroke-width="8"/>']
    used = max(0, min(100, tray["used"]))
    if used:
        angle = math.radians(used * 3.6 - 90)
        x, y = 32 + 26.5 * math.cos(angle), 32 + 26.5 * math.sin(angle)
        parts.append(f'<path d="M32 5.5 A26.5 26.5 0 {int(used > 50)} 1 {x:.6f} {y:.6f}" '
                     f'fill="none" stroke="{tray["color"]}" stroke-width="8" stroke-linecap="round"/>')
    if tray["expected"] >= 0:
        angle = math.radians(tray["expected"] * 3.6 - 90)
        x1, y1 = 32 + 21 * math.cos(angle), 32 + 21 * math.sin(angle)
        x2, y2 = 32 + 32 * math.cos(angle), 32 + 32 * math.sin(angle)
        for color, width in [(colors["background"], 5), (colors["foreground"], 3)]:
            parts.append(f'<path d="M{x1:.6f} {y1:.6f} L{x2:.6f} {y2:.6f}" '
                         f'fill="none" stroke="{color}" stroke-width="{width}"/>')
    name = tray["provider"].lower()
    if name not in {"claude", "codex", "cursor", "grok"}:
        raise ValueError("Select one of the four bundled provider icons.")
    logo = ET.parse(ROOT / "clients/shared/provider-icons" / f"{name}.svg").getroot()
    x, y, width, height = tray["logo_bounds"]
    scale = min(32 / width, 32 / height)
    left, top = 32 - width * scale / 2, 32 - height * scale / 2
    artwork = "".join(ET.tostring(child, encoding="unicode") for child in logo)
    parts.append(f'<g transform="translate({left:.6f} {top:.6f}) scale({scale:.9f}) '
                 f'translate({-x:.6f} {-y:.6f})">{artwork}</g>')
    if tray["secondary"]:
        parts.append(f'<circle cx="53" cy="52" r="8" fill="{tray["secondary_color"]}" '
                     f'stroke="{colors["background"]}" stroke-width="3"/>')
    return "\n".join(parts)


def compose(scene, metadata, output, tray_svg):
    layout = scene["composition"]
    width, padding, gap = layout["width"], layout["padding"], layout["gap"]
    tray_scale = layout["tray_scale"]
    ui_scale = layout.get("ui_scale", 1)
    ui_width, ui_height = metadata["width"] * ui_scale, metadata["height"] * ui_scale
    # Align the high-resolution UI image to the export pixel grid.
    ui_x = round((width - ui_width) * scene["scale"] / 2) / scene["scale"]
    tray_x = (width - 960 * tray_scale) / 2
    tray_y = padding + ui_height + gap
    height = math.ceil(tray_y + 160 * tray_scale + padding)
    if ui_x < 0 or tray_x < 0:
        raise ValueError("The composition must contain the complete UI and tray.")
    root = ET.fromstring(tray_svg)
    for element in list(root):
        if element.get("id") == "tooltip" or element.tag in {f"{{{SVG_NS}}}title", f"{{{SVG_NS}}}desc"}:
            root.remove(element)
    tray_body = "".join(ET.tostring(child, encoding="unicode") for child in root)
    desktop = base64.b64encode((output / "headroom-desktop.png").read_bytes()).decode()
    pointer = tray_x + 200 * tray_scale
    bottom = padding + ui_height
    svg = f'''<svg xmlns="{SVG_NS}" xmlns:xlink="http://www.w3.org/1999/xlink" width="{width}" height="{height}" viewBox="0 0 {width} {height}" role="img" aria-labelledby="title description">
<title id="title">Headroom usage panel and system tray</title>
<desc id="description">The current compact Headroom interface, rendered from production QML with illustrative Claude, ChatGPT, Cursor and Grok readings, above a platform-neutral tray.</desc>
<!-- Generated by docs/renderings/render.py. UI is rendered at {scene["scale"] * ui_scale:g}x logical resolution; tray is vector artwork. -->
<rect x="{ui_x}" y="{padding + 4}" width="{ui_width}" height="{ui_height}" rx="{16 * ui_scale}" fill="#000" opacity=".08"/>
<path d="M{pointer - 9} {bottom - 1} L{pointer} {bottom + 8} L{pointer + 9} {bottom - 1}" fill="{metadata["colors"]["inset"]}" stroke="{metadata["colors"]["selection"]}"/>
<image x="{ui_x}" y="{padding}" width="{ui_width}" height="{ui_height}" xlink:href="data:image/png;base64,{desktop}"/>
<g transform="translate({tray_x} {tray_y}) scale({tray_scale})">{tray_body}</g>
</svg>
'''
    (output / "headroom-overview.svg").write_text(svg, encoding="utf-8")
    return width, height


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--qt-prefix", type=Path, help="Qt 6.12+ installation (or set CMAKE_PREFIX_PATH)")
    parser.add_argument("--scene", type=Path, default=HERE / "scene.json")
    parser.add_argument("--build-dir", type=Path, default=ROOT / ".omo/docs-render-build")
    parser.add_argument("--output-dir", type=Path, default=ROOT / "docs/images")
    parser.add_argument("--skip-build", action="store_true", help="Reuse an already built renderer")
    args = parser.parse_args()
    scene_path = args.scene.resolve()
    scene = json.loads(scene_path.read_text(encoding="utf-8"))
    if scene["scale"] not in {1, 2, 3, 4}:
        parser.error("scale must be 1, 2, 3 or 4")
    build = args.build_dir.resolve()
    output = args.output_dir.resolve()
    output.mkdir(parents=True, exist_ok=True)
    if not args.skip_build:
        command = ["cmake", "-S", HERE, "-B", build, "-DCMAKE_BUILD_TYPE=Release"]
        if args.qt_prefix:
            command.append(f"-DCMAKE_PREFIX_PATH={args.qt_prefix.resolve()}")
        run(*command)
        run("cmake", "--build", build, "--config", "Release", "--target", "headroom-doc-render", "--parallel", "4")
    names = [build / "headroom-doc-render", build / "headroom-doc-render.exe", build / "Release/headroom-doc-render.exe"]
    renderer = next((path for path in names if path.is_file()), None)
    if renderer is None:
        raise FileNotFoundError("Build headroom-doc-render before using --skip-build.")
    ui_scale = scene["composition"].get("ui_scale", 1)
    if not isinstance(ui_scale, (int, float)) or not math.isfinite(ui_scale) or not 0.5 <= ui_scale <= 2:
        parser.error("composition.ui_scale must be between 0.5 and 2")
    # Render QML at the final composed resolution instead of enlarging a bitmap.
    ui_render_scale = scene["scale"] * ui_scale
    env = os.environ.copy()
    env.update(QT_QPA_PLATFORM="offscreen", QT_QUICK_BACKEND="software",
               QT_SCALE_FACTOR=str(ui_render_scale), QT_AUTO_SCREEN_SCALE_FACTOR="0", TZ="UTC")
    # Generate and validate all outputs before replacing the checked-in assets.
    with tempfile.TemporaryDirectory(prefix="headroom-documentation-") as temporary:
        stage = Path(temporary)
        run(renderer, scene_path, stage, env=env)
        metadata = json.loads((stage / "render-metadata.json").read_text())
        if abs(metadata["pixel_width"] - scene["width"] * ui_render_scale) > 1:
            raise ValueError("Unexpected Qt render scale.")
        substitutions = dict(metadata["colors"], icon=tray_icon(metadata),
                             clock_path=metadata["clock_path"], tooltip_path=metadata["tooltip_path"])
        tray_svg = string.Template((HERE / "tray.svg.in").read_text()).substitute(substitutions)
        ET.fromstring(tray_svg)
        (stage / "headroom-tray.svg").write_text(tray_svg, encoding="utf-8")
        size = compose(scene, metadata, stage, tray_svg)
        for asset in ("headroom-tray", "headroom-overview"):
            run(renderer, "--svg", stage / f"{asset}.svg", stage / f"{asset}.png", scene["scale"], env=env)
        for name, expected in [("headroom-desktop", (metadata["pixel_width"], metadata["pixel_height"])),
                               ("headroom-tray", (960 * scene["scale"], 224 * scene["scale"])),
                               ("headroom-overview", tuple(value * scene["scale"] for value in size))]:
            with Image.open(stage / f"{name}.png") as image:
                if image.size != expected or image.mode != "RGBA":
                    raise ValueError(f"Invalid export for {name}: {image.size}, {image.mode}")
                image.verify()
        sources = sorted((ROOT / "clients/desktop/qml").glob("*.qml"))
        sources += [ROOT / "clients/desktop" / name for name in ("usage.cpp", "warning.cpp", "trayvisual.cpp")]
        sources += sorted((ROOT / "clients/shared/provider-icons").glob("*.svg"))
        sources += [HERE / name for name in ("scene.json", "render.cpp", "render.py", "tray.svg.in", "CMakeLists.txt")]
        sources += sorted((HERE / "fonts").glob("*.ttf"))
        metadata["source_sha256"] = {str(path.relative_to(ROOT)): hashlib.sha256(path.read_bytes()).hexdigest()
                                     for path in sources}
        metadata["scene_sha256"] = hashlib.sha256(scene_path.read_bytes()).hexdigest()
        metadata["composition"] = {"width": size[0], "height": size[1], "scale": scene["scale"],
                                   "ui_scale": ui_scale, "tray_scale": scene["composition"]["tray_scale"]}
        (stage / "headroom-render.json").write_text(json.dumps(metadata, indent=2) + "\n", encoding="utf-8")
        for name in ("headroom-desktop.png", "headroom-tray.svg", "headroom-tray.png",
                     "headroom-overview.svg", "headroom-overview.png", "headroom-render.json"):
            shutil.copyfile(stage / name, output / name)
    print(f"Updated {output / 'headroom-overview.png'} ({size[0] * scene['scale']} x {size[1] * scene['scale']})")


if __name__ == "__main__":
    main()